### PR TITLE
magnus update on PT demux intro

### PR DESCRIPTION
**Pull request by fluffy**

### CODE REVIEW

**Comment by aboba** [comment]
@juberti Although it says "PT cannot be used" when it is not unique, it does not specifically say that no PT table entries are made in that case.  To ensure that different implementations interoperate, explicit instructions are better.

**Comment by ekr** [comment]
I basically agree with bernard here. We should describe exactly how you handle PT mux.

**Comment by ekr** [comment]
+1 to Justin and Bernard.

**Comment by juberti** [comment]
@aboba, do you think this overall change would be useful with the PT muxing spelled out? Or is the PT muxing already handled sufficiently elsewhere?

**Comment by juberti** [comment]
Deferring judgement on this one for now

**Comment by aboba** [comment]
@juberti  I think the existing text describes PT multiplexing in a way that is easier to understand and implement.  This text seems less clear (though the intent seems to be the same).

**Comment by juberti** [comment]
Based on feedback from @aboba, not planning to take this change.

**Comment by juberti** [comment]
I'm not totally clear on when PT mux is supposed to be used, given that MID in RTP headers and RTCP SDES is mandatory. That said, this PR doesn't really pertain to that question, and as indicated above, is probably unnecessary.

**Comment by aboba** [comment]
@juberti  PT mux is to ensure that existing applications continue to run, and that they can behave consistently across browsers.  Aside from conferencing applications which use SSRC mux today and are likely to migrate to MIDs, many applications use PT mux because it is simple.

**Pull request closed without merging**
