### PR TITLE
rephrase 'MUST only'

### LINKED ISSUE #660: MUST only is confusing
The bullets on page 45 use the construct "MUST only" three times. This is confusing, and likely to lead to implementors doing the wrong thing. Please rewrite in the form "The 'a=rtcp' line MUST NOT be added unless..."

### PR DESCRIPTION
**Pull request by fluffy**
Fixes #660 

Please review carefully

### CODE REVIEW

**Comment by juberti** [comment]
I'm not sure this reformulation is an improvement - seems like a lot of double negatives. @ekr, wdyt?

**Comment by ekr** [comment]
I think I agree with Justin. I guess I can take a pass at this if Fluffy feels like he has taken his best shot and we don't like it. @fluffy?

**Comment by fluffy** [comment]
Yah - @ekr - see what you would do and either do it or just give me a template of how to eal with one without the double negatives

**Comment by ekr** [comment]
Closing in favor of #706

**Pull request closed without merging**
