### PR TITLE
Remove mapping table for direction attributes. Fixes #292

### LINKED ISSUE #292: Revise S 5.2.4 to refer to transceiver.direction, instead of sender/receiver.active
See https://tools.ietf.org/html/draft-ietf-rtcweb-jsep-14#section-5.2.4

### PR DESCRIPTION
**Pull request by ekr**

### CODE REVIEW

**Comment by juberti** [comment]
Can you separate this from the ICE changes that are also in this PR?

**Comment by ekr** [comment]
Oops, yeah

**Comment by ekr** [comment]
@juberti PTAL

**Comment by juberti** [comment]
LGTM

**Pull request merged**
