### PR TITLE
Switch normative musts/shoulds to MUSTs/SHOULDs

### LINKED ISSUE #977: 2119/8174 Keywords
During EDIT, we modified the following paragraph:

Original:

   The key words "MUST", "MUST NOT", "REQUIRED", "SHALL", "SHALL NOT",
   "SHOULD", "SHOULD NOT", "RECOMMENDED", "MAY", and "OPTIONAL" in this
   document are to be interpreted as described in [RFC2119].

Current:

   The key words "MUST", "MUST NOT", "REQUIRED", "SHALL", "SHALL NOT",
   "SHOULD", "SHOULD NOT", "RECOMMENDED", "NOT RECOMMENDED", "MAY", and
   "OPTIONAL" in this document are to be interpreted as described in
   BCP 14 [RFC2119] [RFC8174] when, and only when, they appear in all
   capitals, as shown here.

This document uses at least one instance of a 2119 keyword in lowercase. 
Please review and let us know if the paragraph about keywords should refer to RFC 2119 (only).

For background: https://www.rfc-editor.org/pipermail/c238/2020-July/000504.html

### PR DESCRIPTION
**Pull request by juberti**
Fixes #977

### CODE REVIEW

**Review by ajeanmahoney — APPROVED** [review]
The new normative text is tagged correctly. Final approval resides with the AD. Thanks!

**Review by fluffy — APPROVED** [review]
I am fine with theses changes. I did not review any of the ones that you did not change.

**Comment by juberti** [comment]
@mskucherawy for approval

**Comment by mskucherawy** [comment]
Approved.  (If I need to say this someplace else, let me know.)

**Pull request merged**
