### PR TITLE
Add explainer paragraph regarding why PT demux is part of the algorithm

### LINKED ISSUE #619: Is the PT table in the demux algo necessary?
BUNDLE mandates sending MID in RTP headers and RTCP messages. What's the rationale for having a second demux mechanism?

### PR DESCRIPTION
**Pull request by juberti**
Fixes #619

### CODE REVIEW

**Comment by fluffy** [comment]
This is not why we do this. If you add the MID for audio calls it ups the peak bandwidth which increases the amount of bandwidth you need to reserver for each call on a satellite link. So by using PT instead of MID, you get more calls on the sat link. Theses are calls where is tracks but few enough it is nowhere even close to running out PTs.

**Comment by juberti** [comment]
OK, I got rid of the 'legacy' terminology. LMK if you want to include the bandwidth rationale (which seems like a modest improvement and may need a detailed explanation)

**Comment by fluffy** [comment]
I like your new text. LGTM

**Comment by juberti** [comment]
@ekr, LMK if you approve or have no opinion on this

**Comment by ekr** [comment]
LGTM.

**Pull request merged**
