### PR TITLE
magnus update on RTCP feedback

### PR DESCRIPTION
**Pull request by fluffy**

### CODE REVIEW

**Comment by aboba** [comment]
Would like to remove the word "pattern" if possible, and I'd like it to be more clear that we are matching against the outgoing SSRC table. But otherwise this snippet looks ok.

**Comment by fluffy** [comment]
I'd like to cover the cases Magnus raised but would prefer specific things instead of treating it as a pattern that people follow. I'd rather try and figure out what we are missing from existing text and figure out how to add it.

**Comment by ekr** [comment]
+1 to Fluffy/Bernard. This whole thing needs to be specifically algorithmic, not just examples

**Comment by juberti** [comment]
I like the way this treats 4585 cases all at once, but agree we should retain the imperative style.

**Comment by gloinul** [comment]
I wrote the text as refering to design pattern with known examples. Call it something else, but there is underlying issue here. This text considers the RTCP feedback types that RTCWeb has considered to use. It is not covering all RTCP messages that exist even today, and it can't cover any future ones. Thus, I tried to write it in a way that allows a person considering a non mentioned RTCP feedback packet type to match what they have to one of the design patterns and add it into that category.

**Comment by gloinul** [comment]
Regarding @aboba comment on outgoing SSRC table. I mostly agree. Of the examples listed it is the outgoing table that are relevant. For any FB message that is a notification, i.e. in response to a request or command on another end-point's SSRC,  there exists the possibility that the used SSRC for sending the request/command is not in the outgoing table. For example if the RTP stack uses one SSRC for RTCP reporting only, not at all for sending any RTP stream. In that case, that SSRC would not be in the outgoing table, but would the addressed part in the RTCP Feedback message. Yes, corner case, but a possibility. 

Also in this case one could have thrid party targeted FB messages that would be addressed to an SSRC belonging to a peer end-point. They would then not be in the outgoing, but possibly in the incoming table.

**Comment by juberti** [comment]
Obsoleted by #548.

**Pull request closed without merging**
