### PR TITLE
expand out short hand notation for Local/remote

### LINKED ISSUE #665: Related to #664, regarding remote description
Section 5.7, first paragraph: similar to above, change "setLocal/RemoteDescription" to "setRemoteDescription."

### PR DESCRIPTION
**Pull request by fluffy**
Fixes #665

### CODE REVIEW

**Comment by juberti** [comment]
Adam's concern here was that the local description could never be invalid, since it was generated by the implementation.

**Comment by ekr** [comment]
Correct. I think you need to either remove setLocal or do: parse and (if setRemote, choke one error).

**Comment by ekr** [comment]
Editor discussion: this paragraph seems redundant so just remove it? @fluffy to look.

**Comment by fluffy** [comment]
@ekr @juberti - ready for re-review

**Pull request merged**
