### PR TITLE
start change log for -16

### PR DESCRIPTION
**Pull request by fluffy**

### CODE REVIEW

**Comment by fluffy** [comment]
Has diffs for PR merged up to commit b92ee53e5fb1b82856a510b7670fb96e5aaa1bc7

**Comment by juberti** [comment]
Can you paste a query with all the PRs merged/issues closed since last draft?

**Comment by fluffy** [comment]
List of PR closed (new to old).

**Comment by fluffy** [comment]
List of bugs closed (new to old)

Should JSEP talk about generating a mid if missing? 

Section 5.8: Document handling of invalid PTs in answer 

Section 5.8: Define PT->media mapping 

Section 5.8: handle header extensions

Describe how onicecandidate indicates end of candidates

Add reference to draft-ietf-mmusic-4572-update

Update to draft-ietf-mmusic-4572-update-05

Placeholder open issue in 6. should be removed 

Open Issue in 5.2.1 

Add Section for createDataChannel editor-ready 

Add section for addTransceiver editor-ready 

Say something about a=rtcp-mux-only 

Revise S 5.2.4 to refer to transceiver.direction, instead of sender/receiver.active

Detail out the steps for addIceCandidate 

Need JSEP anchor for receipt of multiple encodings

**Comment by fluffy** [comment]
has diff up to e8eae82db38150b50c3d2765b963dc63ab52f072 of master

**Comment by fluffy** [comment]
More PR's 


Clarify max-bundle. Fixes #307 

Add RTP demux algorithm 

Clean up end of candidates and m=section/ufrag lookup 

Discuss header extensions in more detail

**Comment by fluffy** [comment]
More Issues closed 


Clarify max-bundle algorithm editor-ready 

Need description of behavior upon end of candidates

Specify demux algorithm for RTP 

Section 5.8: Define PT->media mapping

Section 5.8: Document handling of invalid PTs in answer

**Pull request merged**
