### PR TITLE
Update W3C ref

### PR DESCRIPTION
**Pull request by seanturner**
Addresses GENART review:
https://mailarchive.ietf.org/arch/msg/rtcweb/DcHcqjiwRZdfjZzbMJMDofd8YXU/

### CODE REVIEW

**Review by ekr — APPROVED** [review]
LGTM. @fluffy @juberti ?

**Comment by fluffy** [comment]
Just trying to see how this comes out in th .txt final file - still looking at this

**Comment by fluffy** [comment]
In the .txt file, the refernce from this PR comes out like 


   [W3C.webrtc]
              Jennings, C., Ed., Boström, H., Ed., and J. Bruaroey, Ed.,
              "WebRTC 1.0: Real-time Communication Between Browsers",
              World Wide Web Consortium Recommendation, January 2021,
              <https://www.w3.org/TR/2021/REC-webrtc-20210126/>.

This looks correct to me as it is a stable reference to the REC.

**Review by fluffy — CHANGES_REQUESTED** [review]
I agree with the change from the PR to the dated REC. 

I do not think it should be moved from informative to normative.

**Comment by seanturner** [comment]
@fluffy see #1026.

**Comment by juberti** [comment]
Sounds like we should close this in favor of #1026. I agree with Cullen that informative is probably the right category here as the W3C spec largely depends on JSEP, rather than vice versa.

**Comment by seanturner** [comment]
Yes feel free to close this out in favor of #1026.

**Pull request closed without merging**
