### PR TITLE
fix up W3C ref on rfced-61 version 

### PR DESCRIPTION
**Pull request by fluffy**

### CODE REVIEW

**Comment by fluffy** [comment]
FYI - we should get the Proposed Recommendation version this today and I will update and all going well the Recommendation version ( semi equivalent to an RFC) should be Jan 26

**Comment by fluffy** [comment]
The PR version published and I updated to point at that

**Review by juberti — APPROVED** [review]

**Comment by ajeanmahoney** [comment]
Regarding the name Boström, this can be included as-is in the XML:
`<author fullname="Henrik Boström" initials="H." surname="Boström" role="editor">`

**Comment by ajeanmahoney** [comment]
@fluffy I fixed Boström in PR #999

**Pull request merged**
