### PR TITLE
Fix ref for Issue#927

### PR DESCRIPTION
**Pull request by fluffy**

### CODE REVIEW

**Comment by fluffy** [comment]
Fixes #927

**Comment by juberti** [comment]
I fixed this PR up to reference the rfced branch. @ajeanmahoney, please see if this looks right to you.

**Comment by fluffy** [comment]
Thanks for fixing. I did not understand the correct way to provide that.

**Comment by juberti** [comment]
@ajeanmahoney, should I merge this change and close out #927?

**Comment by ajeanmahoney** [comment]
The new link points to a page that lists 3 editors (Jennings, Boström, Bruaroey).  The citation as constructed lists 7 authors, so I wouldn't close out #927 just yet.  

To fix the issue, the <author> tags need to be constructed as follows (the attribute role="editor" needs to be added for each current editor). For example: 

<author fullname="Cullen Jennings" initials="C." surname="Jennings" role="editor">
              <organization>Cisco</organization>
            </author>

And the entries for the former editors removed. 

Thanks!

**Comment by ajeanmahoney** [comment]
Here's the code example (sigh):

`<author fullname="Cullen Jennings" initials="C." surname="Jennings" role="editor">
              <organization>Cisco</organization>
            </author>`

**Comment by fluffy** [comment]
Sorry - did not see this one and it make the other PR wrong. Will try and sort out

**Comment by fluffy** [comment]
this PR is wrong, don't merge

**Comment by fluffy** [comment]
Replaced with https://github.com/rtcweb-wg/jsep/pull/991

**Pull request closed without merging**
