### PR TITLE
Rfced 60.3 can trickle

### LINKED ISSUE #969: 60.3) Term consistency - canTrickleIceCandidates
>Are "canTrickleIceCandidates" (Section 4.1.15) and "canTrickle property" (Section 5.10) distinct terms? If so, should this distinction be clarified in the text?

Justin: no, they should all be canTrickleIceCandidates.

### PR DESCRIPTION
**Pull request by ajeanmahoney**
all should be canTrickleIceCandidates, removed comment, fixes #969, issue 60.3

### CODE REVIEW

**Comment by juberti** [comment]
OOC, are you doing 'git pull' to bring down the most recent changes to the rfced branch? There are a lot of commits here that have already been merged.

**Comment by ajeanmahoney** [comment]
My process (all run on my local machine on ajeanmahoney/jsep):
git checkout rfced 
git fetch upstream
git merge upstream/rfced
git push origin rfced
git checkout -b branchname
(edits)
git add
git commit
git push --set-upstream origin branchname

Sometimes I merge branchname to my rfced branch: 
git checkout rfced
git merge branch
git push origin rfced
git checkout -b branchname

My previous times working in GitHub (and working with the CLI) have been on repos that I've owned or have been the main contributor to. We didn't use issue tracking or pull requests. The few times I've used PRs on other repos have been minor and informal; I've stayed in the GUI.  

Give me a monkey script that works better, thanks!

**Comment by juberti** [comment]
I think the issue is that your branches are being created from master rather than rfced, so you're not getting the changes that have already been landed on rfced. 

I think I may just switch the setup here to merge rfced into master which would simplify the situation.

**Comment by juberti** [comment]
Will land these PRs first though.

**Comment by ajeanmahoney** [comment]
I think you're right about the branch being created off master. 

I had made the assumption that, if I was already on the rfced branch, then the command `git checkout -b <branchname>` would create a branch off rfced, but it branches off HEAD (master) instead. However, giving the command a start point (`git checkout -b <branchname> rfced`) doesn't seem to fix the stack of commits on the new branch (and this is after merging upstream/rfced).

Perhaps merging rfced into master would make things cleaner.

**Comment by ajeanmahoney** [comment]
Should I continue working on rfced or are we going to switch to working on master?

**Comment by juberti** [comment]
I had some things to attend to and will be OOO later this week, but planning to move to master next week. For now you can continue to work on rfced; you might also want to try creating your branch in this repo rather than in your downstream repo.

**Comment by ajeanmahoney** [comment]
I created a branch off this repo and then created a pull request:
https://github.com/rtcweb-wg/jsep/pull/972
Much cleaner!

**Comment by juberti** [comment]
agreed, thanks for looking into this.

**Pull request merged**
